package uk.ac.rhul.cs.dice.vacuumworld.monitoring.database;

public enum VacuumWorldDatabaseInteractions {
	UPDATE_AGENTS_HISTORIES, UPDATE_DIRTS_HISTORIES, UPDATE_USER_HISTORY, READ_AGENTS_HISTORIES, READ_DIRTS_HISTORIES, READ_USER_HISTORY, READ_AGENT_HISTORY, READ_DIRT_HISTORY;
}